[project]
name = "budget-app2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.2.1",
    "streamlit>=1.52.1",
    "watchdog>=6.0.0",
]

[dependency-groups]
dev = [
    "budget",
    "mypy>=1.15",
]

[tool.uv.sources]
budget = { path = "../../../src/budget", editable = true }

[tool.mypy]
python_version = "3.13"
namespace_packages = true
explicit_package_bases = true
ignore_missing_imports = true
show_error_codes = true
exclude = "(^|/)(\\.venv|\\.mypy_cache|\\.pytest_cache|__pycache__)(/|$)"
