[project]
name = "budget"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "pyarrow>=18.0.0",
    "pandas>=2.2.3",
    "pydantic>=2.9.2",
    "polars>=1.13.1",
    "google-auth-oauthlib>=1.2.1",
    "google-auth-httplib2>=0.2.0",
    "google-api-python-client>=2.153.0",
]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "pandas-stubs>=2.2.3.241009",
    "types-python-dateutil>=2.9.0.20241003",
    "types-requests>=2.32.0.20241016",
    "pytest>=8.3.3",
]

[tool.hatch.build.targets.wheel]
packages = ["wiz/budget"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
