[mypy]
python_version = 3.13
namespace_packages = True
ignore_missing_imports = True
show_error_codes = True
files =
    src/budget/wiz/budget,
    src/evaluation/wiz/evaluation,
    src/interface/wiz/interface,
    src/shared/wiz/shared,
    src/job_app_backend/wiz/job_app_backend
